import chalk from 'chalk';
import type { QuoteResult } from '../core/types.js';
import type { AdvancedRoute } from '../core/lifi-client.js';
import { chainIdToName } from '../core/chain-map.js';
import { formatTokenAmount } from '../core/token-map.js';

export function exportJSON(data: unknown): void {
  console.log(JSON.stringify(data, null, 2));
}

export function exportMarkdownQuote(quote: QuoteResult): void {
  const fromChain = chainIdToName(quote.action.fromChainId);
  const toChain = chainIdToName(quote.action.toChainId);
  const fromSymbol = quote.action.fromToken.symbol;
  const toSymbol = quote.action.toToken.symbol;
  const toAmount = formatTokenAmount(quote.estimate.toAmount, quote.action.toToken.decimals);
  const fromAmount = formatTokenAmount(quote.estimate.fromAmount, quote.action.fromToken.decimals);
  const duration = quote.estimate.executionDuration;
  const timeStr = duration < 60 ? `${duration}s` : `${Math.floor(duration / 60)}m ${duration % 60}s`;

  const totalGas = quote.estimate.gasCosts
    .reduce((sum, g) => sum + parseFloat(g.amountUSD), 0)
    .toFixed(2);

  const steps = quote.includedSteps
    .filter(s => s.tool !== 'feeCollection')
    .map((s, i) => {
      if (s.type === 'cross') return `${i + 1}. Bridge via ${s.toolDetails.name}`;
      if (s.type === 'swap') return `${i + 1}. Swap via ${s.toolDetails.name}`;
      return `${i + 1}. ${s.type} via ${s.toolDetails.name}`;
    });

  const md = `# LI.FI Route Quote

| Field | Value |
|-------|-------|
| From | ${fromAmount} ${fromSymbol} on ${fromChain} |
| To | ~${toAmount} ${toSymbol} on ${toChain} |
| USD Value | $${quote.estimate.fromAmountUSD} → $${quote.estimate.toAmountUSD} |
| Estimated Time | ~${timeStr} |
| Gas Cost | $${totalGas} |
| Bridge | ${quote.toolDetails.name} |
| Slippage | ${(quote.action.slippage * 100).toFixed(1)}% |

## Route Steps

${steps.map(s => `- ${s}`).join('\n')}

---
*Generated by lifi-debug CLI*
`;

  console.log(md);
}

export function exportMarkdownRoutes(routes: AdvancedRoute[]): void {
  if (routes.length === 0) {
    console.log('# No routes found');
    return;
  }

  const fromSymbol = routes[0]!.fromToken.symbol;
  const toSymbol = routes[0]!.toToken.symbol;
  const toDecimals = routes[0]!.toToken.decimals;
  const fromChain = chainIdToName(routes[0]!.fromToken.chainId);
  const toChain = chainIdToName(routes[0]!.toToken.chainId);

  const header = `# LI.FI Route Comparison

**${fromSymbol} (${fromChain}) → ${toSymbol} (${toChain})**

| # | Bridge | Output | USD | Gas | Steps |
|---|--------|--------|-----|-----|-------|`;

  const rows = routes.map((r, i) => {
    const toolName = r.steps.map(s => s.toolDetails.name).join(' + ');
    const toAmount = formatTokenAmount(r.toAmount, toDecimals);
    const gasUSD = r.gasCostUSD ? `$${parseFloat(r.gasCostUSD).toFixed(2)}` : 'N/A';
    const stepCount = r.steps.reduce((sum, s) => sum + (s.includedSteps?.length ?? 1), 0);
    return `| ${i + 1} | ${toolName} | ${toAmount} ${toSymbol} | $${parseFloat(r.toAmountUSD).toFixed(2)} | ${gasUSD} | ${stepCount} |`;
  });

  const md = `${header}
${rows.join('\n')}

---
*Generated by lifi-debug CLI*
`;

  console.log(md);
}

export function renderExportSuccess(format: string): void {
  console.log(chalk.green(`\n  ✅ Exported as ${format.toUpperCase()}\n`));
}
